#!/usr/bin/env python3
"""
Add multilingual translations (en, ko, ja, zh, es, de, fr) to chest-ct structures.json.
Uses standard medical/anatomical terminology for each language.
"""

import json
import os

# Comprehensive translation mapping for all 108 TotalSegmentator structures
# Format: structure_name -> {en, ko, ja, zh, es, de, fr}
TRANSLATIONS = {
    "adrenal_gland_left": {
        "en": "Left Adrenal Gland",
        "ko": "왼쪽 부신",
        "ja": "左副腎",
        "zh": "左肾上腺",
        "es": "Glándula Suprarrenal Izquierda",
        "de": "Linke Nebenniere",
        "fr": "Glande Surrénale Gauche",
    },
    "adrenal_gland_right": {
        "en": "Right Adrenal Gland",
        "ko": "오른쪽 부신",
        "ja": "右副腎",
        "zh": "右肾上腺",
        "es": "Glándula Suprarrenal Derecha",
        "de": "Rechte Nebenniere",
        "fr": "Glande Surrénale Droite",
    },
    "aorta": {
        "en": "Aorta",
        "ko": "대동맥",
        "ja": "大動脈",
        "zh": "主动脉",
        "es": "Aorta",
        "de": "Aorta",
        "fr": "Aorte",
    },
    "atrial_appendage_left": {
        "en": "Left Atrial Appendage",
        "ko": "좌심방이",
        "ja": "左心耳",
        "zh": "左心耳",
        "es": "Orejuela Auricular Izquierda",
        "de": "Linkes Herzohr",
        "fr": "Auricule Gauche",
    },
    "autochthon_left": {
        "en": "Left Autochthonous Back Muscles",
        "ko": "왼쪽 고유등근",
        "ja": "左固有背筋",
        "zh": "左固有背肌",
        "es": "Músculos Autóctonos Izquierdos",
        "de": "Linke Autochthone Rückenmuskulatur",
        "fr": "Muscles Autochtones Gauches",
    },
    "autochthon_right": {
        "en": "Right Autochthonous Back Muscles",
        "ko": "오른쪽 고유등근",
        "ja": "右固有背筋",
        "zh": "右固有背肌",
        "es": "Músculos Autóctonos Derechos",
        "de": "Rechte Autochthone Rückenmuskulatur",
        "fr": "Muscles Autochtones Droits",
    },
    "brachiocephalic_trunk": {
        "en": "Brachiocephalic Trunk",
        "ko": "완두동맥간",
        "ja": "腕頭動脈",
        "zh": "头臂干",
        "es": "Tronco Braquiocefálico",
        "de": "Truncus Brachiocephalicus",
        "fr": "Tronc Brachio-céphalique",
    },
    "brachiocephalic_vein_left": {
        "en": "Left Brachiocephalic Vein",
        "ko": "왼쪽 완두정맥",
        "ja": "左腕頭静脈",
        "zh": "左头臂静脉",
        "es": "Vena Braquiocefálica Izquierda",
        "de": "Linke Vena Brachiocephalica",
        "fr": "Veine Brachio-céphalique Gauche",
    },
    "brachiocephalic_vein_right": {
        "en": "Right Brachiocephalic Vein",
        "ko": "오른쪽 완두정맥",
        "ja": "右腕頭静脈",
        "zh": "右头臂静脉",
        "es": "Vena Braquiocefálica Derecha",
        "de": "Rechte Vena Brachiocephalica",
        "fr": "Veine Brachio-céphalique Droite",
    },
    "clavicula_left": {
        "en": "Left Clavicle",
        "ko": "왼쪽 쇄골",
        "ja": "左鎖骨",
        "zh": "左锁骨",
        "es": "Clavícula Izquierda",
        "de": "Linke Clavicula",
        "fr": "Clavicule Gauche",
    },
    "clavicula_right": {
        "en": "Right Clavicle",
        "ko": "오른쪽 쇄골",
        "ja": "右鎖骨",
        "zh": "右锁骨",
        "es": "Clavícula Derecha",
        "de": "Rechte Clavicula",
        "fr": "Clavicule Droite",
    },
    "colon": {
        "en": "Colon",
        "ko": "결장",
        "ja": "結腸",
        "zh": "结肠",
        "es": "Colon",
        "de": "Kolon",
        "fr": "Côlon",
    },
    "common_carotid_artery_left": {
        "en": "Left Common Carotid Artery",
        "ko": "왼쪽 총경동맥",
        "ja": "左総頸動脈",
        "zh": "左颈总动脉",
        "es": "Arteria Carótida Común Izquierda",
        "de": "Linke Arteria Carotis Communis",
        "fr": "Artère Carotide Commune Gauche",
    },
    "common_carotid_artery_right": {
        "en": "Right Common Carotid Artery",
        "ko": "오른쪽 총경동맥",
        "ja": "右総頸動脈",
        "zh": "右颈总动脉",
        "es": "Arteria Carótida Común Derecha",
        "de": "Rechte Arteria Carotis Communis",
        "fr": "Artère Carotide Commune Droite",
    },
    "costal_cartilages": {
        "en": "Costal Cartilages",
        "ko": "늑연골",
        "ja": "肋軟骨",
        "zh": "肋软骨",
        "es": "Cartílagos Costales",
        "de": "Rippenknorpel",
        "fr": "Cartilages Costaux",
    },
    "duodenum": {
        "en": "Duodenum",
        "ko": "십이지장",
        "ja": "十二指腸",
        "zh": "十二指肠",
        "es": "Duodeno",
        "de": "Duodenum",
        "fr": "Duodénum",
    },
    "esophagus": {
        "en": "Esophagus",
        "ko": "식도",
        "ja": "食道",
        "zh": "食管",
        "es": "Esófago",
        "de": "Ösophagus",
        "fr": "Œsophage",
    },
    "femur_left": {
        "en": "Left Femur",
        "ko": "왼쪽 대퇴골",
        "ja": "左大腿骨",
        "zh": "左股骨",
        "es": "Fémur Izquierdo",
        "de": "Linker Femur",
        "fr": "Fémur Gauche",
    },
    "femur_right": {
        "en": "Right Femur",
        "ko": "오른쪽 대퇴골",
        "ja": "右大腿骨",
        "zh": "右股骨",
        "es": "Fémur Derecho",
        "de": "Rechter Femur",
        "fr": "Fémur Droit",
    },
    "gallbladder": {
        "en": "Gallbladder",
        "ko": "담낭",
        "ja": "胆嚢",
        "zh": "胆囊",
        "es": "Vesícula Biliar",
        "de": "Gallenblase",
        "fr": "Vésicule Biliaire",
    },
    "gluteus_maximus_left": {
        "en": "Left Gluteus Maximus",
        "ko": "왼쪽 대둔근",
        "ja": "左大殿筋",
        "zh": "左臀大肌",
        "es": "Glúteo Mayor Izquierdo",
        "de": "Linker Musculus Gluteus Maximus",
        "fr": "Grand Fessier Gauche",
    },
    "gluteus_maximus_right": {
        "en": "Right Gluteus Maximus",
        "ko": "오른쪽 대둔근",
        "ja": "右大殿筋",
        "zh": "右臀大肌",
        "es": "Glúteo Mayor Derecho",
        "de": "Rechter Musculus Gluteus Maximus",
        "fr": "Grand Fessier Droit",
    },
    "gluteus_medius_left": {
        "en": "Left Gluteus Medius",
        "ko": "왼쪽 중둔근",
        "ja": "左中殿筋",
        "zh": "左臀中肌",
        "es": "Glúteo Medio Izquierdo",
        "de": "Linker Musculus Gluteus Medius",
        "fr": "Moyen Fessier Gauche",
    },
    "gluteus_medius_right": {
        "en": "Right Gluteus Medius",
        "ko": "오른쪽 중둔근",
        "ja": "右中殿筋",
        "zh": "右臀中肌",
        "es": "Glúteo Medio Derecho",
        "de": "Rechter Musculus Gluteus Medius",
        "fr": "Moyen Fessier Droit",
    },
    "gluteus_minimus_left": {
        "en": "Left Gluteus Minimus",
        "ko": "왼쪽 소둔근",
        "ja": "左小殿筋",
        "zh": "左臀小肌",
        "es": "Glúteo Menor Izquierdo",
        "de": "Linker Musculus Gluteus Minimus",
        "fr": "Petit Fessier Gauche",
    },
    "gluteus_minimus_right": {
        "en": "Right Gluteus Minimus",
        "ko": "오른쪽 소둔근",
        "ja": "右小殿筋",
        "zh": "右臀小肌",
        "es": "Glúteo Menor Derecho",
        "de": "Rechter Musculus Gluteus Minimus",
        "fr": "Petit Fessier Droit",
    },
    "heart": {
        "en": "Heart",
        "ko": "심장",
        "ja": "心臓",
        "zh": "心脏",
        "es": "Corazón",
        "de": "Herz",
        "fr": "Cœur",
    },
    "hip_left": {
        "en": "Left Hip Bone",
        "ko": "왼쪽 관골",
        "ja": "左寛骨",
        "zh": "左髋骨",
        "es": "Hueso Coxal Izquierdo",
        "de": "Linkes Os Coxae",
        "fr": "Os Coxal Gauche",
    },
    "hip_right": {
        "en": "Right Hip Bone",
        "ko": "오른쪽 관골",
        "ja": "右寛骨",
        "zh": "右髋骨",
        "es": "Hueso Coxal Derecho",
        "de": "Rechtes Os Coxae",
        "fr": "Os Coxal Droit",
    },
    "humerus_left": {
        "en": "Left Humerus",
        "ko": "왼쪽 상완골",
        "ja": "左上腕骨",
        "zh": "左肱骨",
        "es": "Húmero Izquierdo",
        "de": "Linker Humerus",
        "fr": "Humérus Gauche",
    },
    "humerus_right": {
        "en": "Right Humerus",
        "ko": "오른쪽 상완골",
        "ja": "右上腕骨",
        "zh": "右肱骨",
        "es": "Húmero Derecho",
        "de": "Rechter Humerus",
        "fr": "Humérus Droit",
    },
    "iliac_artery_left": {
        "en": "Left Iliac Artery",
        "ko": "왼쪽 장골동맥",
        "ja": "左腸骨動脈",
        "zh": "左髂动脉",
        "es": "Arteria Ilíaca Izquierda",
        "de": "Linke Arteria Iliaca",
        "fr": "Artère Iliaque Gauche",
    },
    "iliac_artery_right": {
        "en": "Right Iliac Artery",
        "ko": "오른쪽 장골동맥",
        "ja": "右腸骨動脈",
        "zh": "右髂动脉",
        "es": "Arteria Ilíaca Derecha",
        "de": "Rechte Arteria Iliaca",
        "fr": "Artère Iliaque Droite",
    },
    "iliac_vena_left": {
        "en": "Left Iliac Vein",
        "ko": "왼쪽 장골정맥",
        "ja": "左腸骨静脈",
        "zh": "左髂静脉",
        "es": "Vena Ilíaca Izquierda",
        "de": "Linke Vena Iliaca",
        "fr": "Veine Iliaque Gauche",
    },
    "iliac_vena_right": {
        "en": "Right Iliac Vein",
        "ko": "오른쪽 장골정맥",
        "ja": "右腸骨静脈",
        "zh": "右髂静脉",
        "es": "Vena Ilíaca Derecha",
        "de": "Rechte Vena Iliaca",
        "fr": "Veine Iliaque Droite",
    },
    "iliopsoas_left": {
        "en": "Left Iliopsoas Muscle",
        "ko": "왼쪽 장요근",
        "ja": "左腸腰筋",
        "zh": "左髂腰肌",
        "es": "Músculo Iliopsoas Izquierdo",
        "de": "Linker Musculus Iliopsoas",
        "fr": "Muscle Ilio-psoas Gauche",
    },
    "iliopsoas_right": {
        "en": "Right Iliopsoas Muscle",
        "ko": "오른쪽 장요근",
        "ja": "右腸腰筋",
        "zh": "右髂腰肌",
        "es": "Músculo Iliopsoas Derecho",
        "de": "Rechter Musculus Iliopsoas",
        "fr": "Muscle Ilio-psoas Droit",
    },
    "inferior_vena_cava": {
        "en": "Inferior Vena Cava",
        "ko": "하대정맥",
        "ja": "下大静脈",
        "zh": "下腔静脉",
        "es": "Vena Cava Inferior",
        "de": "Vena Cava Inferior",
        "fr": "Veine Cave Inférieure",
    },
    "kidney_left": {
        "en": "Left Kidney",
        "ko": "왼쪽 신장",
        "ja": "左腎臓",
        "zh": "左肾",
        "es": "Riñón Izquierdo",
        "de": "Linke Niere",
        "fr": "Rein Gauche",
    },
    "kidney_right": {
        "en": "Right Kidney",
        "ko": "오른쪽 신장",
        "ja": "右腎臓",
        "zh": "右肾",
        "es": "Riñón Derecho",
        "de": "Rechte Niere",
        "fr": "Rein Droit",
    },
    "liver": {
        "en": "Liver",
        "ko": "간",
        "ja": "肝臓",
        "zh": "肝脏",
        "es": "Hígado",
        "de": "Leber",
        "fr": "Foie",
    },
    "lung_lower_lobe_left": {
        "en": "Left Lung Lower Lobe",
        "ko": "왼쪽 폐 하엽",
        "ja": "左肺下葉",
        "zh": "左肺下叶",
        "es": "Lóbulo Inferior del Pulmón Izquierdo",
        "de": "Linker Lungenunterlappen",
        "fr": "Lobe Inférieur du Poumon Gauche",
    },
    "lung_lower_lobe_right": {
        "en": "Right Lung Lower Lobe",
        "ko": "오른쪽 폐 하엽",
        "ja": "右肺下葉",
        "zh": "右肺下叶",
        "es": "Lóbulo Inferior del Pulmón Derecho",
        "de": "Rechter Lungenunterlappen",
        "fr": "Lobe Inférieur du Poumon Droit",
    },
    "lung_middle_lobe_right": {
        "en": "Right Lung Middle Lobe",
        "ko": "오른쪽 폐 중엽",
        "ja": "右肺中葉",
        "zh": "右肺中叶",
        "es": "Lóbulo Medio del Pulmón Derecho",
        "de": "Rechter Lungenmittellappen",
        "fr": "Lobe Moyen du Poumon Droit",
    },
    "lung_upper_lobe_left": {
        "en": "Left Lung Upper Lobe",
        "ko": "왼쪽 폐 상엽",
        "ja": "左肺上葉",
        "zh": "左肺上叶",
        "es": "Lóbulo Superior del Pulmón Izquierdo",
        "de": "Linker Lungenoberlappen",
        "fr": "Lobe Supérieur du Poumon Gauche",
    },
    "lung_upper_lobe_right": {
        "en": "Right Lung Upper Lobe",
        "ko": "오른쪽 폐 상엽",
        "ja": "右肺上葉",
        "zh": "右肺上叶",
        "es": "Lóbulo Superior del Pulmón Derecho",
        "de": "Rechter Lungenoberlappen",
        "fr": "Lobe Supérieur du Poumon Droit",
    },
    "pancreas": {
        "en": "Pancreas",
        "ko": "췌장",
        "ja": "膵臓",
        "zh": "胰腺",
        "es": "Páncreas",
        "de": "Pankreas",
        "fr": "Pancréas",
    },
    "portal_vein_and_splenic_vein": {
        "en": "Portal Vein and Splenic Vein",
        "ko": "간문맥 및 비장정맥",
        "ja": "門脈および脾静脈",
        "zh": "门静脉和脾静脉",
        "es": "Vena Porta y Vena Esplénica",
        "de": "Pfortader und Milzvene",
        "fr": "Veine Porte et Veine Splénique",
    },
    "prostate": {
        "en": "Prostate",
        "ko": "전립선",
        "ja": "前立腺",
        "zh": "前列腺",
        "es": "Próstata",
        "de": "Prostata",
        "fr": "Prostate",
    },
    "pulmonary_vein": {
        "en": "Pulmonary Vein",
        "ko": "폐정맥",
        "ja": "肺静脈",
        "zh": "肺静脉",
        "es": "Vena Pulmonar",
        "de": "Lungenvene",
        "fr": "Veine Pulmonaire",
    },
    # Ribs - Left 1-12
    "rib_left_1": {
        "en": "Left 1st Rib",
        "ko": "왼쪽 제1늑골",
        "ja": "左第1肋骨",
        "zh": "左第1肋骨",
        "es": "1.ª Costilla Izquierda",
        "de": "Linke 1. Rippe",
        "fr": "1ère Côte Gauche",
    },
    "rib_left_2": {
        "en": "Left 2nd Rib",
        "ko": "왼쪽 제2늑골",
        "ja": "左第2肋骨",
        "zh": "左第2肋骨",
        "es": "2.ª Costilla Izquierda",
        "de": "Linke 2. Rippe",
        "fr": "2ème Côte Gauche",
    },
    "rib_left_3": {
        "en": "Left 3rd Rib",
        "ko": "왼쪽 제3늑골",
        "ja": "左第3肋骨",
        "zh": "左第3肋骨",
        "es": "3.ª Costilla Izquierda",
        "de": "Linke 3. Rippe",
        "fr": "3ème Côte Gauche",
    },
    "rib_left_4": {
        "en": "Left 4th Rib",
        "ko": "왼쪽 제4늑골",
        "ja": "左第4肋骨",
        "zh": "左第4肋骨",
        "es": "4.ª Costilla Izquierda",
        "de": "Linke 4. Rippe",
        "fr": "4ème Côte Gauche",
    },
    "rib_left_5": {
        "en": "Left 5th Rib",
        "ko": "왼쪽 제5늑골",
        "ja": "左第5肋骨",
        "zh": "左第5肋骨",
        "es": "5.ª Costilla Izquierda",
        "de": "Linke 5. Rippe",
        "fr": "5ème Côte Gauche",
    },
    "rib_left_6": {
        "en": "Left 6th Rib",
        "ko": "왼쪽 제6늑골",
        "ja": "左第6肋骨",
        "zh": "左第6肋骨",
        "es": "6.ª Costilla Izquierda",
        "de": "Linke 6. Rippe",
        "fr": "6ème Côte Gauche",
    },
    "rib_left_7": {
        "en": "Left 7th Rib",
        "ko": "왼쪽 제7늑골",
        "ja": "左第7肋骨",
        "zh": "左第7肋骨",
        "es": "7.ª Costilla Izquierda",
        "de": "Linke 7. Rippe",
        "fr": "7ème Côte Gauche",
    },
    "rib_left_8": {
        "en": "Left 8th Rib",
        "ko": "왼쪽 제8늑골",
        "ja": "左第8肋骨",
        "zh": "左第8肋骨",
        "es": "8.ª Costilla Izquierda",
        "de": "Linke 8. Rippe",
        "fr": "8ème Côte Gauche",
    },
    "rib_left_9": {
        "en": "Left 9th Rib",
        "ko": "왼쪽 제9늑골",
        "ja": "左第9肋骨",
        "zh": "左第9肋骨",
        "es": "9.ª Costilla Izquierda",
        "de": "Linke 9. Rippe",
        "fr": "9ème Côte Gauche",
    },
    "rib_left_10": {
        "en": "Left 10th Rib",
        "ko": "왼쪽 제10늑골",
        "ja": "左第10肋骨",
        "zh": "左第10肋骨",
        "es": "10.ª Costilla Izquierda",
        "de": "Linke 10. Rippe",
        "fr": "10ème Côte Gauche",
    },
    "rib_left_11": {
        "en": "Left 11th Rib",
        "ko": "왼쪽 제11늑골",
        "ja": "左第11肋骨",
        "zh": "左第11肋骨",
        "es": "11.ª Costilla Izquierda",
        "de": "Linke 11. Rippe",
        "fr": "11ème Côte Gauche",
    },
    "rib_left_12": {
        "en": "Left 12th Rib",
        "ko": "왼쪽 제12늑골",
        "ja": "左第12肋骨",
        "zh": "左第12肋骨",
        "es": "12.ª Costilla Izquierda",
        "de": "Linke 12. Rippe",
        "fr": "12ème Côte Gauche",
    },
    # Ribs - Right 1-12
    "rib_right_1": {
        "en": "Right 1st Rib",
        "ko": "오른쪽 제1늑골",
        "ja": "右第1肋骨",
        "zh": "右第1肋骨",
        "es": "1.ª Costilla Derecha",
        "de": "Rechte 1. Rippe",
        "fr": "1ère Côte Droite",
    },
    "rib_right_2": {
        "en": "Right 2nd Rib",
        "ko": "오른쪽 제2늑골",
        "ja": "右第2肋骨",
        "zh": "右第2肋骨",
        "es": "2.ª Costilla Derecha",
        "de": "Rechte 2. Rippe",
        "fr": "2ème Côte Droite",
    },
    "rib_right_3": {
        "en": "Right 3rd Rib",
        "ko": "오른쪽 제3늑골",
        "ja": "右第3肋骨",
        "zh": "右第3肋骨",
        "es": "3.ª Costilla Derecha",
        "de": "Rechte 3. Rippe",
        "fr": "3ème Côte Droite",
    },
    "rib_right_4": {
        "en": "Right 4th Rib",
        "ko": "오른쪽 제4늑골",
        "ja": "右第4肋骨",
        "zh": "右第4肋骨",
        "es": "4.ª Costilla Derecha",
        "de": "Rechte 4. Rippe",
        "fr": "4ème Côte Droite",
    },
    "rib_right_5": {
        "en": "Right 5th Rib",
        "ko": "오른쪽 제5늑골",
        "ja": "右第5肋骨",
        "zh": "右第5肋骨",
        "es": "5.ª Costilla Derecha",
        "de": "Rechte 5. Rippe",
        "fr": "5ème Côte Droite",
    },
    "rib_right_6": {
        "en": "Right 6th Rib",
        "ko": "오른쪽 제6늑골",
        "ja": "右第6肋骨",
        "zh": "右第6肋骨",
        "es": "6.ª Costilla Derecha",
        "de": "Rechte 6. Rippe",
        "fr": "6ème Côte Droite",
    },
    "rib_right_7": {
        "en": "Right 7th Rib",
        "ko": "오른쪽 제7늑골",
        "ja": "右第7肋骨",
        "zh": "右第7肋骨",
        "es": "7.ª Costilla Derecha",
        "de": "Rechte 7. Rippe",
        "fr": "7ème Côte Droite",
    },
    "rib_right_8": {
        "en": "Right 8th Rib",
        "ko": "오른쪽 제8늑골",
        "ja": "右第8肋骨",
        "zh": "右第8肋骨",
        "es": "8.ª Costilla Derecha",
        "de": "Rechte 8. Rippe",
        "fr": "8ème Côte Droite",
    },
    "rib_right_9": {
        "en": "Right 9th Rib",
        "ko": "오른쪽 제9늑골",
        "ja": "右第9肋骨",
        "zh": "右第9肋骨",
        "es": "9.ª Costilla Derecha",
        "de": "Rechte 9. Rippe",
        "fr": "9ème Côte Droite",
    },
    "rib_right_10": {
        "en": "Right 10th Rib",
        "ko": "오른쪽 제10늑골",
        "ja": "右第10肋骨",
        "zh": "右第10肋骨",
        "es": "10.ª Costilla Derecha",
        "de": "Rechte 10. Rippe",
        "fr": "10ème Côte Droite",
    },
    "rib_right_11": {
        "en": "Right 11th Rib",
        "ko": "오른쪽 제11늑골",
        "ja": "右第11肋骨",
        "zh": "右第11肋骨",
        "es": "11.ª Costilla Derecha",
        "de": "Rechte 11. Rippe",
        "fr": "11ème Côte Droite",
    },
    "rib_right_12": {
        "en": "Right 12th Rib",
        "ko": "오른쪽 제12늑골",
        "ja": "右第12肋骨",
        "zh": "右第12肋骨",
        "es": "12.ª Costilla Derecha",
        "de": "Rechte 12. Rippe",
        "fr": "12ème Côte Droite",
    },
    "sacrum": {
        "en": "Sacrum",
        "ko": "천골",
        "ja": "仙骨",
        "zh": "骶骨",
        "es": "Sacro",
        "de": "Sakrum",
        "fr": "Sacrum",
    },
    "scapula_left": {
        "en": "Left Scapula",
        "ko": "왼쪽 견갑골",
        "ja": "左肩甲骨",
        "zh": "左肩胛骨",
        "es": "Escápula Izquierda",
        "de": "Linke Scapula",
        "fr": "Omoplate Gauche",
    },
    "scapula_right": {
        "en": "Right Scapula",
        "ko": "오른쪽 견갑골",
        "ja": "右肩甲骨",
        "zh": "右肩胛骨",
        "es": "Escápula Derecha",
        "de": "Rechte Scapula",
        "fr": "Omoplate Droite",
    },
    "skull": {
        "en": "Skull",
        "ko": "두개골",
        "ja": "頭蓋骨",
        "zh": "颅骨",
        "es": "Cráneo",
        "de": "Schädel",
        "fr": "Crâne",
    },
    "small_bowel": {
        "en": "Small Bowel",
        "ko": "소장",
        "ja": "小腸",
        "zh": "小肠",
        "es": "Intestino Delgado",
        "de": "Dünndarm",
        "fr": "Intestin Grêle",
    },
    "spinal_cord": {
        "en": "Spinal Cord",
        "ko": "척수",
        "ja": "脊髄",
        "zh": "脊髓",
        "es": "Médula Espinal",
        "de": "Rückenmark",
        "fr": "Moelle Épinière",
    },
    "spleen": {
        "en": "Spleen",
        "ko": "비장",
        "ja": "脾臓",
        "zh": "脾脏",
        "es": "Bazo",
        "de": "Milz",
        "fr": "Rate",
    },
    "sternum": {
        "en": "Sternum",
        "ko": "흉골",
        "ja": "胸骨",
        "zh": "胸骨",
        "es": "Esternón",
        "de": "Sternum",
        "fr": "Sternum",
    },
    "stomach": {
        "en": "Stomach",
        "ko": "위",
        "ja": "胃",
        "zh": "胃",
        "es": "Estómago",
        "de": "Magen",
        "fr": "Estomac",
    },
    "subclavian_artery_left": {
        "en": "Left Subclavian Artery",
        "ko": "왼쪽 쇄골하동맥",
        "ja": "左鎖骨下動脈",
        "zh": "左锁骨下动脉",
        "es": "Arteria Subclavia Izquierda",
        "de": "Linke Arteria Subclavia",
        "fr": "Artère Sous-clavière Gauche",
    },
    "subclavian_artery_right": {
        "en": "Right Subclavian Artery",
        "ko": "오른쪽 쇄골하동맥",
        "ja": "右鎖骨下動脈",
        "zh": "右锁骨下动脉",
        "es": "Arteria Subclavia Derecha",
        "de": "Rechte Arteria Subclavia",
        "fr": "Artère Sous-clavière Droite",
    },
    "superior_vena_cava": {
        "en": "Superior Vena Cava",
        "ko": "상대정맥",
        "ja": "上大静脈",
        "zh": "上腔静脉",
        "es": "Vena Cava Superior",
        "de": "Vena Cava Superior",
        "fr": "Veine Cave Supérieure",
    },
    "thyroid_gland": {
        "en": "Thyroid Gland",
        "ko": "갑상선",
        "ja": "甲状腺",
        "zh": "甲状腺",
        "es": "Glándula Tiroides",
        "de": "Schilddrüse",
        "fr": "Glande Thyroïde",
    },
    "trachea": {
        "en": "Trachea",
        "ko": "기관",
        "ja": "気管",
        "zh": "气管",
        "es": "Tráquea",
        "de": "Trachea",
        "fr": "Trachée",
    },
    "urinary_bladder": {
        "en": "Urinary Bladder",
        "ko": "방광",
        "ja": "膀胱",
        "zh": "膀胱",
        "es": "Vejiga Urinaria",
        "de": "Harnblase",
        "fr": "Vessie",
    },
    # Vertebrae - Cervical
    "vertebrae_C7": {
        "en": "Vertebra C7",
        "ko": "제7경추",
        "ja": "第7頸椎",
        "zh": "第7颈椎",
        "es": "Vértebra C7",
        "de": "Wirbel C7",
        "fr": "Vertèbre C7",
    },
    # Vertebrae - Lumbar
    "vertebrae_L1": {
        "en": "Vertebra L1",
        "ko": "제1요추",
        "ja": "第1腰椎",
        "zh": "第1腰椎",
        "es": "Vértebra L1",
        "de": "Wirbel L1",
        "fr": "Vertèbre L1",
    },
    "vertebrae_L2": {
        "en": "Vertebra L2",
        "ko": "제2요추",
        "ja": "第2腰椎",
        "zh": "第2腰椎",
        "es": "Vértebra L2",
        "de": "Wirbel L2",
        "fr": "Vertèbre L2",
    },
    "vertebrae_L3": {
        "en": "Vertebra L3",
        "ko": "제3요추",
        "ja": "第3腰椎",
        "zh": "第3腰椎",
        "es": "Vértebra L3",
        "de": "Wirbel L3",
        "fr": "Vertèbre L3",
    },
    "vertebrae_L4": {
        "en": "Vertebra L4",
        "ko": "제4요추",
        "ja": "第4腰椎",
        "zh": "第4腰椎",
        "es": "Vértebra L4",
        "de": "Wirbel L4",
        "fr": "Vertèbre L4",
    },
    "vertebrae_L5": {
        "en": "Vertebra L5",
        "ko": "제5요추",
        "ja": "第5腰椎",
        "zh": "第5腰椎",
        "es": "Vértebra L5",
        "de": "Wirbel L5",
        "fr": "Vertèbre L5",
    },
    # Vertebrae - Sacral
    "vertebrae_S1": {
        "en": "Vertebra S1",
        "ko": "제1천추",
        "ja": "第1仙椎",
        "zh": "第1骶椎",
        "es": "Vértebra S1",
        "de": "Wirbel S1",
        "fr": "Vertèbre S1",
    },
    # Vertebrae - Thoracic
    "vertebrae_T1": {
        "en": "Vertebra T1",
        "ko": "제1흉추",
        "ja": "第1胸椎",
        "zh": "第1胸椎",
        "es": "Vértebra T1",
        "de": "Wirbel T1",
        "fr": "Vertèbre T1",
    },
    "vertebrae_T2": {
        "en": "Vertebra T2",
        "ko": "제2흉추",
        "ja": "第2胸椎",
        "zh": "第2胸椎",
        "es": "Vértebra T2",
        "de": "Wirbel T2",
        "fr": "Vertèbre T2",
    },
    "vertebrae_T3": {
        "en": "Vertebra T3",
        "ko": "제3흉추",
        "ja": "第3胸椎",
        "zh": "第3胸椎",
        "es": "Vértebra T3",
        "de": "Wirbel T3",
        "fr": "Vertèbre T3",
    },
    "vertebrae_T4": {
        "en": "Vertebra T4",
        "ko": "제4흉추",
        "ja": "第4胸椎",
        "zh": "第4胸椎",
        "es": "Vértebra T4",
        "de": "Wirbel T4",
        "fr": "Vertèbre T4",
    },
    "vertebrae_T5": {
        "en": "Vertebra T5",
        "ko": "제5흉추",
        "ja": "第5胸椎",
        "zh": "第5胸椎",
        "es": "Vértebra T5",
        "de": "Wirbel T5",
        "fr": "Vertèbre T5",
    },
    "vertebrae_T6": {
        "en": "Vertebra T6",
        "ko": "제6흉추",
        "ja": "第6胸椎",
        "zh": "第6胸椎",
        "es": "Vértebra T6",
        "de": "Wirbel T6",
        "fr": "Vertèbre T6",
    },
    "vertebrae_T7": {
        "en": "Vertebra T7",
        "ko": "제7흉추",
        "ja": "第7胸椎",
        "zh": "第7胸椎",
        "es": "Vértebra T7",
        "de": "Wirbel T7",
        "fr": "Vertèbre T7",
    },
    "vertebrae_T8": {
        "en": "Vertebra T8",
        "ko": "제8흉추",
        "ja": "第8胸椎",
        "zh": "第8胸椎",
        "es": "Vértebra T8",
        "de": "Wirbel T8",
        "fr": "Vertèbre T8",
    },
    "vertebrae_T9": {
        "en": "Vertebra T9",
        "ko": "제9흉추",
        "ja": "第9胸椎",
        "zh": "第9胸椎",
        "es": "Vértebra T9",
        "de": "Wirbel T9",
        "fr": "Vertèbre T9",
    },
    "vertebrae_T10": {
        "en": "Vertebra T10",
        "ko": "제10흉추",
        "ja": "第10胸椎",
        "zh": "第10胸椎",
        "es": "Vértebra T10",
        "de": "Wirbel T10",
        "fr": "Vertèbre T10",
    },
    "vertebrae_T11": {
        "en": "Vertebra T11",
        "ko": "제11흉추",
        "ja": "第11胸椎",
        "zh": "第11胸椎",
        "es": "Vértebra T11",
        "de": "Wirbel T11",
        "fr": "Vertèbre T11",
    },
    "vertebrae_T12": {
        "en": "Vertebra T12",
        "ko": "제12흉추",
        "ja": "第12胸椎",
        "zh": "第12胸椎",
        "es": "Vértebra T12",
        "de": "Wirbel T12",
        "fr": "Vertèbre T12",
    },
}


def main():
    filepath = r"C:\NoAddsMakingApps\BodyAtlas\public\data\chest-ct\structures.json"

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    structures = data["structures"]
    updated = 0
    missing = []

    for struct in structures:
        name = struct["name"]
        if name in TRANSLATIONS:
            struct["displayName"] = TRANSLATIONS[name]
            updated += 1
        else:
            missing.append(name)
            print(f"WARNING: No translation for '{name}'")

    print(f"\nUpdated {updated}/{len(structures)} structures")
    if missing:
        print(f"Missing translations: {missing}")

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Wrote updated file to {filepath}")

    # Verify
    with open(filepath, "r", encoding="utf-8") as f:
        verify = json.load(f)
    sample = verify["structures"][0]
    print(f"\nSample verification - {sample['name']}:")
    for lang, val in sample["displayName"].items():
        print(f"  {lang}: {val}")

    # Check all have 7 languages
    all_good = True
    for s in verify["structures"]:
        langs = set(s["displayName"].keys())
        expected = {"en", "ko", "ja", "zh", "es", "de", "fr"}
        if langs != expected:
            print(f"ERROR: {s['name']} has languages {langs}, expected {expected}")
            all_good = False
    if all_good:
        print("\nAll 108 structures have all 7 language translations!")


if __name__ == "__main__":
    main()
